set nocompatible               " be iMproved
filetype off                   " required!

set rtp+=/usr/lib/python3.3/site-packages/powerline/bindings/vim/
set rtp+=~/.vim/bundle/vundle/
set laststatus=2 " for powerline
call vundle#rc()

" let Vundle manage Vundle
" required! 
Bundle 'gmarik/vundle'

" My Bundles here:
"
" original repos on github
Bundle 'kien/ctrlp.vim'
Bundle 'tpope/vim-rails.git'
Bundle 'rstacruz/sparkup', {'rtp': 'vim/'}
Bundle 'noah/vim256-color'
Bundle 'kchmck/vim-coffee-script'
Bundle 'rodjek/vim-puppet'
Bundle 'jgdavey/tslime.vim'
Bundle 'jgdavey/vim-turbux'
Bundle 'gkz/vim-ls'
Bundle 'Blackrush/vim-gocode'
Bundle 'othree/html5.vim'
Bundle 'othree/vim-coffee-script'
Bundle 'noprompt/vim-yardoc'
Bundle 'scrooloose/nerdtree'
Bundle 'ervandew/supertab'
Bundle 'majutsushi/tagbar'
" vim-scripts repos
Bundle 'EasyMotion'
" Bundle 'FuzzyFinder'

" non github repos
" Bundle 'git://git.wincent.com/command-t.git'

filetype plugin indent on     " required!
"
" Brief help
" :BundleList          - list configured bundles
" :BundleInstall(!)    - install(update) bundles
" :BundleSearch(!) foo - search(or refresh cache first) for foo
" :BundleClean(!)      - confirm(or auto-approve) removal of unused bundles
"
" see :h vundle for more details or wiki for FAQ
" NOTE: comments after Bundle command are not allowed..

set t_Co=256
set tabstop=2                    " Global tab width.
set shiftwidth=2                 " And again, related.
set expandtab                    " Use spaces instead of tabs

colorscheme wombat256mod
syntax on

autocmd FileType eruby  setlocal shiftwidth=4 tabstop=4
autocmd FileType java  setlocal shiftwidth=4 tabstop=4
autocmd FileType javascript  setlocal shiftwidth=4 tabstop=4
au BufRead,BufNewFile *.tpl set filetype=html
au BufRead,BufNewFile *.jst.ejs set filetype=html
au BufRead,BufNewFile *.js set filetype=javascript 

" --- vim-turbux
let g:no_turbux_mappings = 1
map <leader>rt <Plug>SendTestToTmux
map <leader>rT <Plug>SendFocusedTestToTmux
let g:turbux_command_rspec  = 'spring rspec'        " default: rspec
map <C-n> :NERDTreeToggle<CR>
