export PYTHONPATH=/usr/lib/python3.3/site-packages
export LANG=zh_TW.UTF-8
export LC_ALL=zh_TW.UTF-8
# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

# Set to the name theme to load.
# Look in ~/.oh-my-zsh/themes/
#export ZSH_THEME="robbyrussell"
export ZSH_THEME="eastwood"

# Set to this to use case-sensitive completion
# export CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
export DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# export DISABLE_LS_COLORS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git ruby rails)

source $ZSH/oh-my-zsh.sh
unsetopt correct_all # dont check command

# Customize to your needs...
export PAGER='less'
export EDITOR='vim'
export PATH="/opt/java/bin/:/home/tka/bin/:$PATH"
export PATH="/home/tka/Project/android/android-sdk-linux_x86/platform-tools:$PATH"
export PATH="/opt/google/chrome:$PATH"
export JAVA_HOME="/opt/java/"
#export PATH="$HOME/.rbenv/bin:$PATH"

alias open='xdg-open'
alias nfs_server='sudo mount 192.168.1.133:/ server'

alias 'hitfm'='mplayer http://bcr.media.hinet.net/RA000036'
PATH=/usr/share/java/apache-ant/bin:$PATH
alias 'be'='bundle exec'
alias 'fireapp'='~/Project/Compass/FireApp/packages/linux/fire.app/run.sh'
alias 'rcs'='rails c --sandbox'
#export RUBY_HEAP_MIN_SLOTS=1000000
#export RUBY_HEAP_SLOTS_INCREMENT=1000000
#export RUBY_HEAP_SLOTS_GROWTH_FACTOR=1
#export RUBY_GC_MALLOC_LIMIT=1000000000
#export RUBY_HEAP_FREE_MIN=500000
#export RUBY_FREE_MIN=200000

eval "$(fasd --init auto)"
alias v='f -e vim' # quick opening files with vim
alias m='f -e mplayer' # quick opening files with mplayer
alias o='a -e xdg-open' # quick opening files with xdg-open

PATH=$HOME/Project/golang/bin:$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
GOPATH=/home/tka/Project/golang
